"""Regenerate presentation examples through real operations in an isolated fixture."""
import sys,shutil
from pathlib import Path
import argparse
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
sys.path.insert(0,str(Path(__file__).resolve().parent))
parser=argparse.ArgumentParser(description='Export a synthetic isolated editorial scenario.')
parser.add_argument('--output',required=True)
args=parser.parse_args()
output=Path(args.output).resolve()
if '.agile-flow' in output.parts or (output/'.agile-flow').exists():parser.error('Choose an example export directory, not a managed product.')
from test_editorial import EditorialStoreTests
x=EditorialStoreTests();x.setUp()
x.op('initialize',project={'name':'Bookly','purpose':'Let a sole operator offer self-service appointments with an auditable booking result.','background':'Synthetic editorial fixture; no live product or real acceptance is represented.','vision':'Appointments without manual coordination.','mission':'Make availability and booking outcomes clear.','users':[{'actor':'Customer','need':'Choose an available slot','value':'Book without calling'},{'actor':'Operator','need':'See confirmed bookings','value':'Avoid overlapping commitments'}],'objectives':[{'objective':'Persist one booking','evidence':'Read the stored booking','status':'Proposed'}],'scope':['One calendar','One operator'],'exclusions':['Payments','Multiple organizations'],'success_factors':['Persistent data','Clear user feedback'],'confirmed_facts':['This is a synthetic demonstration.'],'assumptions':['One calendar is sufficient for the pilot.'],'open_questions':['Which pilot group will provide feedback?'],'references':['Synthetic test scenario'],'next_step':'Evaluate the pilot feedback before expanding scope.'})
x.op('update-roadmap',document={'direction':'Prove a reliable booking, then expand scheduling capabilities.','versions':[{'version':'v0.1.0','stage':'Booking foundation','intended_outcome':'One persistent booking','capabilities':['Availability','Confirmation'],'dependencies':['Choose pilot calendar'],'status':'planned'},{'version':'v0.2.0','stage':'Schedule changes','intended_outcome':'Controlled rescheduling','capabilities':['Change booking','Notify customer'],'dependencies':['v0.1.0'],'status':'proposed'}],'milestones':[{'milestone':'First pilot booking','version':'v0.1.0','evidence':'Observed customer feedback'}],'assumptions':['Pilot before expanding'],'uncertainties':['Notification channel'],'adaptation_criteria':['Revise the plan if pilot users cannot complete a booking.'],'release_references':[{'version':'v0.1.0','document':'[Booking release](release/v0.1.0/release-0.1.0.md)'}]})
x.op('update-backlog',item={'purpose':'Book independently','value':'Less coordination','users':[{'actor':'Customer','need':'Reserve a slot','value':'Avoid calls'}],'outcome':'A customer can reserve one available slot.','scope':['One calendar'],'exclusions':['Recurring bookings'],'success_indicators':[{'indicator':'Booking completion','target':'Observed in pilot','evidence':'Not measured'}],'priority':'Resolve the basic booking need first.','order':1,'references':['Synthetic owner request']})
x.op('update-release',release={'id':'v0.1.0','objective':'Demonstrate a complete booking with one pilot calendar.','item_ids':['BL-0001'],'users':[{'user':'Pilot customer','value':'Book independently','evidence':'Observed booking'}],'mvp':{'hypothesis':'Customers can book without contacting the operator.','early_users':'One pilot group','minimum_scope':'Availability and one persistent booking','learning_questions':[{'question':'Can a customer finish unaided?','method':'Observe the pilot','decision':'Refine or extend the workflow'}]},'exit_conditions':[{'condition':'A booking persists','evidence':'Persistence test','result':'Pending user review'}],'exclusions':['Payments']})
x.op('plan-iteration',iteration={'release_id':'v0.1.0','goal':'One complete booking','scope':'Calendar and persistence','exclusions':'Notifications','technical_plan':'Persist a booking through a small service boundary.','tasks':[{'id':'TASK-01','story':'US-0001','action':'Implement booking persistence','evidence':'Stored record','status':'planned'}],'verification_plan':[{'requirement':'US-0001 / DOD-01','check':'Persistence','method':'Read after write','evidence':'Test transcript'}]})
for kind,detail in [('US',{'story':{'actor':'Customer','capability':'reserve a slot','benefit':'book without calling'}}),('NFR',{'quality_attribute':'Latency','applicability':'Calendar lookup','target':'p95 under 200 ms','verification_method':'Synthetic load test'}),('BUG',{'observed':'Two bookings for one slot','expected':'One booking','impact':'Operator conflict','reproduction':['Open a slot','Submit twice']}),('TCH',{'technical_objective':'Separate persistence from UI','approach':'Add a repository boundary','components':['Booking service']}),('SPK',{'question':'Which notification channel fits the pilot?','work_limit':'Two hours','expected_output':'Comparison','findings':'Not investigated'})]:
 x.op('update-story',story={'parent_id':'BL-0001','iteration_id':'ITER-001','type':kind,'purpose':kind+' bounded booking work','scope':'One calendar','exclusions':'Multi-tenant scheduling','estimate':2,'criteria':[{'id':'AC-01','condition':'A free slot is selected','result':'One booking persists'}],'dod':[{'id':'DOD-01','requirement':'Verify persistence','evidence':'Synthetic test transcript'}],**detail})
x.authorize()
x.op('prepare',iteration_id='ITER-001',increment={'item_ids':['US-0001'],'objective':'Persist booking','scope':'One calendar','authorization':'DEC-0001'})
x.op('start',increment_id='INC-0001');(x.root/'booking.txt').write_text('Synthetic booking')
x.op('mark-implemented',increment_id='INC-0001')
check=x.store.inspect()['increments'][0]['required_checks'][0]
for result in ['failed','passed']:
 x.op('record-evidence',evidence={'increment_id':'INC-0001','check':check,'result':result,'scope':'Persistence only','paths':['booking.txt'],'method':'Synthetic read-after-write scenario','expected':'One record','observed':'No record' if result=='failed' else 'One record','limitations':'Synthetic fixture; no live user test.','environment':{'type':'isolated fixture'}})
x.op('update-report',iteration_id='ITER-001',document='verification',fields={'scope':[{'increment_id':'INC-0001','revision':1,'item_ids':['US-0001'],'artifact':'booking.txt','environment':'Isolated fixture'}],'conclusion':'The synthetic persistence check passed; live product behavior has not been evaluated.'})
x.op('record-review',review={'increment_id':'INC-0001','decision':'partial','accepted_parts':['US-0001/AC-01: One booking persists'],'user_quote':'Synthetic user: accept persistence only; evaluate usability later.','message_reference':'Synthetic test fixture'})
x.op('update-report',iteration_id='ITER-001',document='review',fields={'presented_result':[{'increment_id':'INC-0001','revision':1,'scope':'Persistence','limits':'No live UI evaluation'}],'unresolved_feedback':[{'question':'Is the UI understandable?','impact':'Pilot usability unknown','action':'Observe a pilot user'}]})
x.op('record-improvement',iteration_id='ITER-001',improvement={'observation':'The first persistence check exposed a missing write.','adjustment':'Add a read-after-write check earlier.','target_cycle':'Next iteration','source':'Synthetic EVD-0001'})
x.op('update-report',iteration_id='ITER-001',document='retrospective',fields={'retain':[{'practice':'Separate verification and acceptance','benefit':'Avoid overstating completion','observation':'Partial review remains explicit'}]})
out=output;out.mkdir(parents=True,exist_ok=True)
for path in x.store.inventory():
 target=out/path;target.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(x.store.directory/path,target)
print(out)
x.doCleanups()
